version: '3.4'

services:
  webspa:
    image: registry.infopulse.local/pacelicsrv-prod/webspa
    build:
      context: .    
      dockerfile: ./Dckerfile
    environment:
      - VERSION=1
      - ENV=itea
    ports:
      - "8000:80"
